- name: Install the latest mysql-server
  ansible.builtin.dnf:
    name: mysql-server
    state: latest

- name: start nginx service
  ansible.builtin.systemd_service:
    state: started
    name: mysqld
    enabled: true
    daemon_reload: true

- name: Remove file (delete file)
  ansible.builtin.file:
    path: /usr/share/nginx/html/*
    state: absent

- name: Make a directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Download frontend code
  ansible.builtin.get_url:
    url: curl -o /tmp/frontend.zip https://expense-artifacts.s3.amazonaws.com/expense-frontend-v2.zip
    dest: /tmp/frontend.zip

- name: unarchive frontend code
  ansible.builtin.unarchive:
    src: /tmp/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: copy expense conf
  ansible.builtin.template:
    src: expense.conf
    dest: /etc/systemd/system/expense.conf

- name: start nginx server
  ansible.builtin.systemd_service:
    name: nginx
    state: restarted
    enabled: true
    daemon_reload: true

